version: '3.8'

services:
  # OpenSearch service
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  # OpenSearch Dashboards (optional - for viewing data)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  # Your FastAPI application
  real-estate-api:
    build: .
    container_name: real-estate-api
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_INDEX=properties
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    volumes:
      - ./app:/app/app  # Mount your app directory for development
    restart: unless-stopped

volumes:
  opensearch-data:

networks:
  opensearch-net: